# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: '$(tag) $(Build.BuildId)'  


- stage: Push
  displayName: Pushing the image
  jobs:
    - job: Push
      steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'dockerhub-token'  # Your Docker Hub service connection name
            repository: 'alikhan24/docker-auto'        # Your Docker Hub repository name
            command: 'push'
            tags: '$(tag) $(Build.BuildId)'            # Use the same tag from the Build stage
